# Generated by Django 4.0.3 on 2022-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('avatar', models.FilePathField(max_length=256)),
                ('type', models.IntegerField()),
                ('region', models.CharField(max_length=256)),
                ('project', models.TextField()),
                ('regis_time', models.TimeField()),
                ('last_login_time', models.TimeField()),
                ('donate_history', models.TextField()),
                ('share_mail_history', models.CharField(max_length=512)),
            ],
        ),
    ]
