# Generated by Django 4.0.3 on 2022-03-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_alter_project_end_time_alter_project_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
