# Generated by Django 4.0.3 on 2022-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_rename_email_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(max_length=64),
        ),
    ]
