# Generated by Django 4.0.3 on 2022-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_alter_project_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='project',
            name='charity',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
