# Generated by Django 4.0.3 on 2022-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_rename_passwd_user_password_project_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charity_avatar',
            field=models.FilePathField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
