# Generated by Django 4.0.3 on 2022-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_project_charity_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_type',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
