# Generated by Django 4.0.3 on 2022-03-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_user_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency_type',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
