# Generated by Django 4.0.3 on 2022-03-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0009_project_currency_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currency_type',
        ),
    ]
