# Generated by Django 4.0.3 on 2022-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0010_remove_project_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
