# Generated by Django 3.1.3 on 2022-03-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_project_status'),
        ('DataBase', '0011_auto_20220321_1931'),
    ]

    operations = [
    ]
