# Generated by Django 4.0.3 on 2022-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0012_merge_20220321_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='DProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, unique=True)),
                ('uid', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('intro', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('charity', models.CharField(max_length=256)),
                ('charity_avatar', models.FilePathField(max_length=256)),
                ('background_image', models.FilePathField(max_length=256)),
                ('status', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('current_num', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('donate_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('avatar', models.FilePathField(max_length=256)),
                ('type', models.IntegerField()),
                ('region', models.CharField(max_length=256)),
                ('currency_type', models.CharField(max_length=256)),
                ('project', models.TextField()),
                ('regis_time', models.IntegerField()),
                ('last_login_time', models.IntegerField()),
                ('donate_history', models.TextField()),
                ('share_mail_history', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='param',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
