# Generated by Django 4.0.3 on 2022-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0013_dproject_duser_delete_project_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='hide',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
