# Generated by Django 4.0.3 on 2022-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0014_duser_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='dproject',
            name='product_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dproject',
            name='subscription_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
